### ISSUE TITLE
Failed to start

### ISSUE THREAD

**Issue by qomosoloto** [ekonstantinidis/gitify#205]
I can't start gitify via running 'npm install && npm start',the error output here:
```
App threw an error when running [TypeError: Cannot read property '0' of null]
A JavaScript error occurred in the main process
Uncaught Exception:
TypeError: Cannot read property '0' of null
    at Object.<anonymous> (/home/qeeker/code-repo/NODEJS/electron/gitify/main.js:25:43)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at loadApplicationPackage (/home/qeeker/code-repo/NODEJS/electron/gitify/node_modules/electron-prebuilt/dist/resources/default_app.asar/main.js:252:23)
    at Object.<anonymous> (/home/qeeker/code-repo/NODEJS/electron/gitify/node_modules/electron-prebuilt/dist/resources/default_app.asar/main.js:292:5)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
```

**Comment by ekonstantinidis** [comment]
Hello @qomosoloto! Sorry for the late reply! I think what's missing is that you also need to do `npm run build` to compile the source code. Once you do that you can then do `npm run watch` and make any changes to the source code.
