### ISSUE TITLE
Any plans for linux (ubuntu) support?

### ISSUE THREAD

**Issue by caske33** [ekonstantinidis/gitify#32]

**Comment by ekonstantinidis** [comment]
There should be no issues but unfortunately I do not have a linux desktop(neither windows - for the windows version) so it's not easy for me to test it. Feel free to test it if you want and let me know how it goes!

**Comment by caske33** [comment]
I unfortunately get an exception: (after git clone, npm install and then npm start)
```
Uncaught Exception:
TypeError: Cannot read property 'hide' of undefined
    at EventEmitter.<anonymous> (/home/jens/Desktop/gitify/main.js:97:11)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:166:7)
```

and this in my console

```
[25998:0530/232933:ERROR:browser_main_loop.cc(173)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
[25998:0530/232933:WARNING:accelerator_util.cc(185)] Invalid accelerator token: command
[25998:0530/232933:WARNING:accelerator_util.cc(185)] Invalid accelerator token: command
[26031:0530/232933:INFO:renderer_main.cc(200)] Renderer process started
[25998:0530/232934:WARNING:accelerator_util.cc(185)] Invalid accelerator token: command
[25998:0530/232934:WARNING:accelerator_util.cc(185)] Invalid accelerator token: command
[26031:0530/232948:INFO:child_thread_impl.cc(725)] ChildThreadImpl::EnsureConnected()
```

it sort of runs, but I don't see any text and can't log in.

**Comment by ekonstantinidis** [comment]
Aah just had a look and it makes sense. This happens because of the way the Electron's `Tray` is trying to position `BrowserWindow` on the screen. Currently on the click of the tray, I'm doing `showWindow(bounds)` but `bounds` according to Electron [docs](https://github.com/atom/electron/blob/master/docs/api/tray.md#event-clicked) are only defined for OSX. So a solution could be something like (in [function showWindow](https://github.com/ekonstantinidis/gitify/blob/master/main.js#L45)):

    function showWindow (bounds) {
        var defaultX = 200;
        var options = {
            x: defaultX || bounds.x - ((opts.width / 2) || 200) + (bounds.width / 2)
            // Same for y
            ...
        }
    }

Here is an [example](https://github.com/maxogden/menubar/blob/master/index.js#L73). If it gets too complicated I could have a look at some point during next week.

**Comment by caske33** [comment]
See #41

**Comment by ekonstantinidis** [comment]
Closing this one - Track #128 for progress :smile:
